# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editar_livro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Editar_Livro(object):
    def setupUi(self, MainWindow):
        # Configurações básicas da janela principal
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 444)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Título da página "Editar Livro"
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 10, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        # Campo para o ano de publicação do livro
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 230, 541, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_ano_publicacao = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_ano_publicacao.setObjectName("lineEdit_ano_publicacao")
        self.horizontalLayout_4.addWidget(self.lineEdit_ano_publicacao)
        
        # Campo para o título do livro
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 80, 541, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_titulo_livro = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_titulo_livro.setObjectName("lineEdit_titulo_livro")
        self.horizontalLayout.addWidget(self.lineEdit_titulo_livro)
        
        # Campo para o autor principal do livro
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 130, 541, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_autor_principal = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_autor_principal.setObjectName("lineEdit_autor_principal")
        self.horizontalLayout_2.addWidget(self.lineEdit_autor_principal)
        
        # Campo para a quantidade de páginas do livro
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 180, 541, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_quantidade_paginas = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_quantidade_paginas.setObjectName("lineEdit_quantidade_paginas")
        self.horizontalLayout_3.addWidget(self.lineEdit_quantidade_paginas)
        
        # Botão para voltar à tela anterior
        self.pushButton_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_voltar.setGeometry(QtCore.QRect(50, 300, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_voltar.setStyleSheet(" border-radius: 8px;\n"
"background-color: rgb(190, 190, 190);")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        
        # Botão para confirmar a edição do livro
        self.pushButton_add_livro = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_livro.setGeometry(QtCore.QRect(430, 300, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add_livro.setFont(font)
        self.pushButton_add_livro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_add_livro.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
" border-radius: 8px;")
        self.pushButton_add_livro.setObjectName("pushButton_add_livro")
        
        # Configurações da barra de menu e status
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        # Definição dos textos para todos os elementos da interface
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Editar Livro"))
        self.label_5.setText(_translate("MainWindow", "Ano de publicação:"))
        self.label_2.setText(_translate("MainWindow", "Título do livro:"))
        self.label_3.setText(_translate("MainWindow", "Autor principal:"))
        self.label_4.setText(_translate("MainWindow", "Quantidade de páginas:"))
        self.pushButton_voltar.setText(_translate("MainWindow", "Voltar"))
        self.pushButton_add_livro.setText(_translate("MainWindow", " Editar livro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Editar_Livro()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
