version: '3.9'

services:
  source:
    build: .
    command: python main.py source
    container_name: source
    depends_on:
      - loadbalance1
      - loadbalance2
    volumes:
      - ./resultados:/resultados
    networks:
      - sdnet

  loadbalance1:
    build: .
    command: python main.py loadbalance 2000 "service1:4001,service2:4002"
    container_name: loadbalance1
    ports:
      - "2000:2000"
    depends_on:
      - service1
      - service2
    networks:
      - sdnet

  loadbalance2:
    build: .
    command: python main.py loadbalance 3000 "service3:4100,service4:4101"
    container_name: loadbalance2
    ports:
      - "3000:3000"
    depends_on:
      - service3
      - service4
    networks:
      - sdnet

  service1:
    build: .
    command: python main.py service 4001 100 distilbert
    container_name: service1
    networks:
      - sdnet
    ports:
      - "4001:4001"

  service2:
    build: .
    command: python main.py service 4002 100 distilbert
    container_name: service2
    networks:
      - sdnet
    ports:
      - "4002:4002"

  service3:
    build: .
    command: python main.py service 4100 100 distilbert
    container_name: service3
    networks:
      - sdnet
    ports:
      - "4100:4100"

  service4:
    build: .
    command: python main.py service 4101 100 distilbert
    container_name: service4
    networks:
      - sdnet
    ports:
      - "4101:4101"

networks:
  sdnet:
    driver: bridge
